version: '3.8'

services:
  mysql:
    image: mysql:8.0       # MySQL 8.0 이미지 사용
    container_name: spring_sample_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # 루트 비밀번호 설정
      MYSQL_DATABASE: spring_sample         # 기본으로 생성할 데이터베이스 이름
      MYSQL_USER: customuser            # 사용자 계정 생성
      MYSQL_PASSWORD: a123456789    # 사용자 비밀번호 설정
    ports:
      - "3310:3306"  # 호스트의 3310 포트를 컨테이너의 3306 포트로 매핑
    volumes:
      - mysql_data:/var/lib/mysql        # MySQL 데이터를 호스트에 영구 저장

volumes:
  mysql_data:
    driver: local